// Generated by CoffeeScript 1.6.3
(function() {
  var coffee, person, _i, _j, _k, _len, _len1, _len2;

  for (_i = 0, _len = people.length; _i < _len; _i++) {
    person = people[_i];
    if (person.age > 18) {
      console.log(person.name);
    }
  }

  for (_j = 0, _len1 = people.length; _j < _len1; _j++) {
    person = people[_j];
    if (person.age > 18) {
      console.log(person.name);
    }
  }

  for (_k = 0, _len2 = coffeeList.length; _k < _len2; _k++) {
    coffee = coffeeList[_k];
    if (!(typeof coffee.isRussian === "function" ? coffee.isRussian() : void 0)) {
      addCoffee(coffee);
    }
  }

}).call(this);
