// Generated by CoffeeScript 1.6.3
(function() {
  var Coffee, DrinkLink, coffee,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Coffee = (function() {
    function Coffee(name, level) {
      this.name = name;
      this.level = level;
    }

    Coffee.prototype.isRussian = function() {
      return this.name === 'Russian';
    };

    return Coffee;

  })();

  coffee = new Coffee('Luiz', 2);

  Coffee = (function() {
    function Coffee(name, level) {
      this.name = name;
      this.level = level != null ? level : 0;
    }

    Coffee.prototype.isRussian = function() {
      return this.name === 'Russian';
    };

    return Coffee;

  })();

  Coffee = (function(_super) {
    __extends(Coffee, _super);

    function Coffee(name, level) {
      this.name = name;
      this.level = level != null ? level : 0;
    }

    Coffee.prototype.serve = function() {
      if (this.sleeve === !true) {
        return false;
      }
      return Coffee.__super__.serve.call(this);
    };

    return Coffee;

  })(Drink);

  DrinkLink = (function() {
    function DrinkLink() {}

    DrinkLink.prototype.watchClick = function() {
      return $('a').click(function() {
        return $(this).css('color', '#F00');
      });
    };

    return DrinkLink;

  })();

  DrinkLink = (function() {
    function DrinkLink(linkClicked) {
      this.linkClicked = linkClicked != null ? linkClicked : false;
    }

    DrinkLink.prototype.watchClick = function() {
      var _this = this;
      return $('.drink a').click(function(event) {
        $(event.target).css('color', '#F00');
        return _this.linkClicked = true;
      });
    };

    return DrinkLink;

  })();

}).call(this);
