// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('#newCoffee a').click(function() {
      return alert('New coffee added');
    });
  });

  $(function() {
    var name;
    name = prompt('Name of coffee:');
    return alert("New coffee added: " + name);
  });

  $(function() {
    return $('#newCoffee a').click(function() {
      var coffee, name;
      name = prompt('Name of coffee: ');
      coffee = $("<li>" + name + "</li>");
      return $('ul.drink').append(coffee);
    });
  });

  $('.drink li a').click(function(e) {
    e.preventDefault();
    return alert($(this).text());
  });

  $('.drink li').mouseenter(function() {
    return $(this).find('span').show;
  });

  $('.drink li').mouseleave(function() {
    return $(this).find('span').hide;
  });

  $('.drink li').hover(function() {
    return $(this).find('span').show();
  }, function() {
    return $(this).find('span').hide();
  });

}).call(this);
