// Generated by CoffeeScript 1.6.3
(function() {
  var message;

  if (caffeineLevel > 5) {
    alert('High Caffeine Level');
  }

  if (caffeineLevel > 5) {
    alert('Too High');
  } else {
    alert('OK');
  }

  if (!coffeeReady) {
    alert('Please wait 5 more minutes.');
  }

  if ((lowLevel < newLevel && newLevel < highLevel)) {
    alert('OK');
  } else {
    alert('abnormal coffeine level');
  }

  message = (function() {
    switch (newLevel) {
      case 1:
        return 'Out of bed yet?';
      case 2:
        return 'Good morning!';
      default:
        return 'You should stop while you can';
    }
  })();

  if (typeof newLevel !== "undefined" && newLevel !== null) {
    checkLevel(newLevel);
  } else {
    resetLevel();
  }

}).call(this);
